#!/usr/bin/env bash
# shellcheck disable=SC1090

# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marko Kungla
# See the LICENSE file for full licensing details.

# This file is subject to the Apache License Version 2.0, as stated in the LICENSE file
# at the time of creation. Check Git history for further details.

# -----------------------------------------------------------------------------
# Script Information
# -----------------------------------------------------------------------------
# Description: Run Discord PTB setup.
# Usage: ./setup
# Author: Marko Kungla
# Created: 2025-02-02
# Dependencies: ./lib/asdf-godot.bash
# ScriptType: Required
# Notes:
# URL: https://asdf-vm.com/plugins/create.html#bin-install

# -----------------------------------------------------------------------------
# Example Usage
# -----------------------------------------------------------------------------
# ./setup
#
# -----------------------------------------------------------------------------

set -euo pipefail

current_script_path=${BASH_SOURCE[0]}
plugin_dir=$(dirname $(dirname "$(dirname "$current_script_path")"))

# shellcheck source=./lib/asdf-discord-ptb.bash
source "${plugin_dir}/lib/asdf-discord-ptb.bash"

data_dir=$HOME/.local/share
applications_dir="${data_dir}/applications"
pixmaps_dir="${data_dir}/pixmaps"
discord_dir="$(dirname $(dirname $(asdf which discord-ptb)))"
resources_dir="${plugin_dir}/res"

mkdir -p $pixmaps_dir

mkdir -p $applications_dir

echo "resource: discord-ptb.desktop (copy)"
desktop_file_src="${resources_dir}/discord-ptb.desktop"
desktop-file-validate "$desktop_file_src"
cp $desktop_file_src "${applications_dir}/discord-ptb.desktop"

if command -v gsettings &>/dev/null; then
	# Get the current icon theme using gsettings
	echo "resources: discord-ptb.png (copy)"
	icon_theme=$(gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g")
	icon_dir_root="${HOME}/.local/share/icons/${icon_theme}"
	mkdir -p ${icon_dir_root}/{16x16,32x32,48x48,128x128}/apps

	cp "${resources_dir}/discord.png" "$icon_dir_root/16x16/apps/discord-ptb.png"
	cp "${resources_dir}/discord.png" "$icon_dir_root/32x32/apps/discord-ptb.png"
	cp "${resources_dir}/discord.png" "$icon_dir_root/48x48/apps/discord-ptb.png"
	cp "${resources_dir}/discord.png" "$icon_dir_root/128x128/apps/discord-ptb.png"

	gtk-update-icon-cache -f -t $icon_dir_root
fi

# echo "data_dir: $data_dir"
# echo "applications_dir: $applications_dir"
# echo "pixmaps_dir: $pixmaps_dir"
# echo "resources_dir: $resources_dir"
# echo "discord_dir: $discord_dir"
# echo "current_script_path: $current_script_path"
